In [14]:
import pandas as pd
import numpy as np

In [15]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [16]:
data = pd.read_csv('traffic.csv')

In [13]:
print('matplotlib version:' , mpl.__version__)

matplotlib version: 3.5.1


In [19]:
data.shape

(13, 74)

# find and replacing missing values

In [22]:
data.isnull()

الشهر  حادث تلفيات  حادث اصابات  حادث وفيات   مجموع عدد الحوادث  السبت  \
0   False        False        False       False               False  False   
1   False        False        False       False               False  False   
2   False        False        False       False               False  False   
3   False        False        False       False               False  False   
4   False        False        False       False               False  False   
5   False        False        False       False               False  False   
6   False        False        False       False               False  False   
7   False        False        False       False               False  False   
8   False        False        False       False               False  False   
9   False        False        False       False               False  False   
10  False        False        False       False               False  False   
11  False        False        False       False               False  False   
12  False        False        False       False               False  False   

    الا حد  الاثنين  الثلاثاء  الا ربعاء  ...  تجاوز غير نظامى  \
0    False    False     False      False  ...            False   
1    False    False     False      False  ...            False   
2    False    False     False      False  ...            False   
3    False    False     False      False  ...            False   
4    False    False     False      False  ...            False   
5    False    False     False      False  ...            False   
6    False    False     False      False  ...            False   
7    False    False     False      False  ...            False   
8    False    False     False      False  ...            False   
9    False    False     False      False  ...            False   
10   False    False     False      False  ...            False   
11   False    False     False      False  ...            False   
12   False    False     False      False  ...            False   

    عدم التقيد بالاشارة  السرعة الزائدة  السائق تحت تأثير مخدر  اخرى.1  \
0                 False           False                  False   False   
1                 False           False                  False   False   
2                 False           False                  False   False   
3                 False           False                  False   False   
4                 False           False                  False   False   
5                 False           False                  False   False   
6                 False           False                  False   False   
7                 False           False                  False   False   
8                 False           False                  False   False   
9                 False           False                  False   False   
10                False           False                  False   False   
11                False           False                  False   False   
12                False           False                  False   False   

    مجموع الحوادث حسب سبب الحادث  عدد المصابين  عدد المتوفين (القتلى)   سليم  \
0                          False         False                  False  False   
1                          False         False                  False  False   
2                          False         False                  False  False   
3                          False         False                  False  False   
4                          False         False                  False  False   
5                          False         False                  False  False   
6                          False         False                  False  False   
7                          False         False                  False  False   
8                          False         False                  False  False   
9                          False         False                  False  False   
10                         False         False                  False

# splitting the dataset into independent and dependent

In [23]:
x=data.iloc[:,:-1].values
x

array([['محرم', 5047.0, 277.0, 75.0, 5399.0, 919.0, 781.0, 625.0, 814.0,
        702.0, 775.0, 783.0, 5399.0, 2819.0, 2580.0, 5399.0, 2452.0,
        2947.0, 5399.0, 1214.0, 1561.0, 63.0, 984.0, 1475.0, 102.0, 0.0,
        5399.0, 'محرم', 2417.0, 4583.0, 4390.0, 1264.0, 274.0, 12928.0,
        9522.0, 3406.0, 12928.0, 8115.0, 4813.0, 12928.0, 12901.0, 27.0,
        12928.0, 7892.0, 2480.0, 0.0, 0.0, 2556.0, 12928.0, 2556.0,
        8611.0, 1761.0, 12928.0, 1647.0, 1542.0, 0.0, 1.0, 0.0, 1132.0,
        261.0, 816.0, 5399.0, 1022.0, 974.0, 891.0, 1208.0, 1304.0, 0.0,
        0.0, 5399.0, 393.0, 100.0, 12435.0],
       ['صفر', 5941.0, 255.0, 78.0, 6274.0, 1427.0, 1407.0, 1434.0,
        857.0, 421.0, 388.0, 340.0, 6274.0, 4589.0, 1685.0, 6274.0,
        5367.0, 907.0, 6274.0, 849.0, 663.0, 45.0, 79.0, 1062.0, 55.0,
        0.0, 2753.0, 'صفر', 1843.0, 2281.0, 2452.0, 2053.0, 1012.0,
        9641.0, 5968.0, 3673.0, 9641.0, 4883.0, 4758.0, 9641.0, 9594.0,
        47.0, 9641.0, 5072.0, 2375.

In [24]:
y=data.iloc[:,3].values
y

array([ 75.,  78.,  87.,  79.,  81.,  79.,  65.,  63.,  71.,  80.,  54.,
        86., 898.])

In [30]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encoder_x=LabelEncoder()
x[:,0]=label_encoder_x.fit_transform(x[:,0])
OneHot_encoder=OneHotEncoder()
x=OneHot_encoder.fit_transform(x).toarray()
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]]
